window.event_data = {
  CONST: {
    MOBILE_ONLY: true,
    VERSION_ID: "e95c5d3f-985d-42f2-a9e5-dc0b059518a5",
    AUTO_SAVE_DRAFT: true,
    AUTO_SAVE_INFO_USER: false,
    AUTO_COMPLETE_FORM_IN_POPUP: false,
    SEND_TO_THANK_PAGE: true,
    GG_ADS_CONSENT_MODE: false,
    GG_TAG_MANAGER_CONSENT_MODE: false,
    MOBILE_WIDTH: 420,
    DESKTOP_WIDTH: 960,
    PAGE_ID: "65234e83-78c0-47ab-bef0-09b16b98421f11",
    TITLE: "THƯ MỜI CƯỚI MẪU ĐỎ TRẮNG",
    COUNTRY: "84",
    TYPE: 1,
    COPY_MESSAGE: { Success: "Đã sao chép!", Failed: "Sao chép thất bại!" },
    REGEX_PHONE_VALIDATOR:
      "^(\\+84|84|0)(3([2-9])|5(2|5|6|8|9)|7(0|[6-9])|8([1-9])|9([0-4]|[6-9]))([0-9]{7})$",
    DEFAULT_KEYS: [
      "email",
      "full_name",
      "first_name",
      "last_name",
      "address",
      "phone_number",
      "province_id",
      "district_id",
      "commune_id",
      "province_id/district_id/commune_id",
    ],
    GOOGLE_API_KEY: "AIzaSyBtswC9pVaBFryGs_42G4ZJKw-U0XBCUTU",
    BODY_FONT_SIZE: 12,
    NOTIFY_IMG_DEFAULT:
      "https://content.pancake.vn/1/4b/52/7f/e7/666682ecfee619a3451cf2566aba653946dc13bfe52f47456f186874.png",
    LOCALES_TIME: {
      vietnam: "vi-VN",
      english: "en-US",
      indonesian: "id-ID",
      filipino: "fil-PH",
      khmer: "km-KH",
      thai: "th-TH",
      malay: "ms-MY",
    },
    GRID_ICON_NEXT:
      '<img src="https://content.pancake.vn/1/d8/88/b5/1f/ce7bea1db3f2c535a89a2c99988aeba8d3a361b2c72c9d08950d10e7.svg">',
    GRID_ICON_PREV:
      '<img src="https://content.pancake.vn/1/31/23/51/e5/41806a12b05813bfc36f3ad3d1a580aa060a9d8f1736cc38e197a61f.svg">',
    PLACEHOLDER_IMAGE:
      "https://content.pancake.vn/1/s752x752/fwebp/54/69/e4/13/d02869f068e9b7c043efc7c551d2042a678a104b32495639f71c33a1.png",
    ICON_FLASH_SALE:
      "https://content.pancake.vn/1/ae/3e/08/81/2358d47a6632c080e27a4da079b6f6ce3cf0dde0168be316c4f27b96.png",
    LANG_LIST_PROD_CURRENCY: {
      STILL: { VND: "Còn", THB: "คลัง", IDR: "Tetap", USD: "Still" },
      PROD: { VND: "sản phẩm", THB: "ชิ้น", IDR: "produk", USD: "product" },
      ADD_TO_CART: {
        VND: "Thêm vào giỏ hàng",
        THB: "หยิบใส่ตะกร้า",
        IDR: "Masukkan ke keranjang",
        USD: "Add to cart",
      },
      QUANTITY: {
        VND: "Số lượng",
        THB: "ปริมาณ",
        IDR: "Kuantitas",
        USD: "Quantity",
      },
      BUY_NOW: {
        VND: "Mua ngay",
        THB: "ซื้อเลย",
        IDR: "Beli sekarang",
        USD: "Buy now",
      },
      CODE_PROD: {
        VND: "Mã sản phẩm",
        THB: "รหัสสินค้า",
        IDR: "Kode Produk",
        USD: "Code product",
      },
      SEARCH_PROD: {
        VND: "Tìm kiếm sản phẩm",
        THB: "ค้นหาสินค้า",
        IDR: "Cari produk",
        USD: "Search product",
      },
      DESCRIPTION: {
        VND: "Mô tả",
        USD: "Description",
        THB: "อธิบาย",
        IDR: "menggambarkan",
      },
      SOLD: { VND: "Đã bán", USD: "Sold", THB: "ขายแล้ว", IDR: "Terjual" },
      NOT_EMPTY: {
        VND: "Không được để trống",
        USD: "Not Empty",
        THB: "เว้นว่างไว้ไม่ได้",
        IDR: "tidak boleh dikosongkan",
      },
      NO_FIND_PROD: {
        VND: "Không tìm thấy sản phẩm",
        USD: "No products found",
        THB: "ไม่พบสินค้า",
        IDR: "Tidak ada produk yang ditemukan",
      },
      DISCOUNT: { VND: "GIẢM", USD: "OFF", THB: "ส่วนลด", IDR: "DISKON" },
      SOLD_OUT: {
        VND: "SẮP CHÁY HÀNG",
        USD: "SOLD OUT SOON",
        THB: "ขายหมดเร็วๆ นี้",
        IDR: "segera terjual",
      },
      USE_CODE: { VND: "Nhập mã", USD: "Use", THB: "ใช้", IDR: "menggunakan" },
      APPLY: { VND: "ÁP DỤNG", USD: "APPLY", THB: "นำมาใช้", IDR: "BERLAKU" },
      BONUS: { VND: "Tặng kèm", USD: "Bonus", THB: "โบนัส", IDR: "bonus" },
      ORG_PRICE: {
        VND: "Giá gốc",
        USD: "Full price",
        THB: "ค่าใช้จ่าย",
        IDR: "Biaya",
      },
      PRICE: { VND: "Giá bán", USD: "Price", THB: "ราคา", IDR: "Harga" },
      COUPON_SUCCESS: {
        VND: "Đã áp dụng coupon!",
        USD: "Coupon applied!",
        THB: "ใช้คูปองแล้ว!",
        IDR: "Kupon berlaku!",
      },
      COUPON_FAILED: {
        VND: "Mã coupon không khả dụng!",
        USD: "Invalid coupon!",
        THB: "คูปองไม่ถูกต้อง!",
        IDR: "Kupon tidak valid!",
      },
      COUPON_EMPTY: {
        VND: "Vui lòng nhập coupon!",
        USD: "Please enter coupon!",
        THB: "กรุณากรอกคูปอง!",
        IDR: "Silakan masukkan kupon!",
      },
      HOUR: { VND: "Giờ", USD: "Hours", THB: "ชั่วโมง", IDR: "Jam" },
      MINUTE: { VND: "Phút", USD: "Minutes", THB: "นาที", IDR: "Menit" },
      SECOND: { VND: "Giây", USD: "Seconds", THB: "ที่สอง", IDR: "Kedua" },
      SALE_COUNTDOWN: {
        VND: "Thời gian khuyến mại chỉ còn",
        USD: "Promotion end in",
        THB: "โปรโมชั่นหมดเขต",
        IDR: "Promosi berakhir pada",
      },
      COPY_SUCCESS: {
        VND: "Đã sao chép!",
        USD: "Copied!",
        THB: "คัดลอกแล้ว!",
        IDR: "Disalin!",
      },
      COPY_FAILED: {
        VND: "Sao chép thất bại!",
        USD: "Copy Failed!",
        THB: "คัดลอกไม่สำเร็จ!",
        IDR: "Penyalinan gagal!",
      },
      WARNING_SURVEY: {
        VND: "Chọn giá trị trong survey",
        USD: "Select values in the survey",
        THB: "เลือกค่าที่ต้องการในแบบสำรวจ",
        IDR: "Pilih nilai dalam survei",
      },
    },
    ALLOW_PLAY_MULTIPLE_VIDEO: false,
  },
  runtime: {
    vm: {
      "1toiquem": {
        type: "section",
        specials: {
          boxShadow: "",
          imageCompression: true,
          pageLoadEvent: "none",
        },
        id: "1toiquem",
        children: [
          "j6ac06mu",
          "3subauj7",
          "q1wlsumy",
          "4aeii491",
          "bnrugie4",
          "hoyb400n",
          "dqyi2rbc",
          "3udt7eao",
          "oob4nyp3",
          "np891vuj",
          "pqtxq0p8",
          "djaowtuq",
          "76hn3zct",
          "ywnx3zmg",
          "1qpgocgm",
          "40pygk87",
          "53vnzuwe",
          "hnewlzw3",
          "9r8tifvf",
        ],
      },
      j6ac06mu: {
        type: "text-block",
        specials: { tag: "h2", text: "Mời Cưới" },
        id: "j6ac06mu",
        desktop: {
          animation: {
            delay: 0,
            duration: 2,
            name: "fadeInDown",
            repeat: null,
          },
          fontSize: "90",
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 2,
            name: "fadeInDown",
            repeat: null,
          },
          fontSize: "90",
        },
        $parent: "1toiquem",
      },
      "3subauj7": {
        type: "image-block",
        specials: {
          compressible: true,
          imageCompression: true,
          isTransparent: true,
          src: "https://statics.pancake.vn/web-media/83/bf/ec/8c/773c7f08f555f31211f154f366ad6d216542348db720bd983c604278-w:1429-h:2000-l:151240-t:image/png.png",
        },
        id: "3subauj7",
        events: [
          {
            action: "show_hide_element",
            animationOut: null,
            appTarget: "",
            hoverColor: "",
            id: "9rlyzve8",
            onlyMode: "hide",
            target: "w-3subauj7",
            type: "click",
          },
          {
            action: "show_hide_element",
            animation: "pulse",
            animationOut: null,
            appTarget: "",
            hoverColor: "",
            id: "w753pw9g",
            onlyMode: "show",
            target: "w-3udt7eao",
            type: "click",
          },
          {
            action: "show_hide_element",
            animation: "pulse",
            appTarget: "",
            hoverColor: "",
            id: "c1vx7bcc",
            onlyMode: "show",
            target: "w-q1wlsumy",
            type: "click",
          },
          {
            action: "show_hide_element",
            animation: null,
            appTarget: "",
            hoverColor: "",
            id: "2l2bjext",
            onlyMode: "show",
            scrollMore: 6,
            target: "w-4aeii491",
            type: "click",
          },
          {
            action: "show_hide_element",
            animation: null,
            appTarget: "",
            hoverColor: "",
            id: "eup0xsqn",
            onlyMode: "show",
            target: "w-dqyi2rbc",
            type: "click",
          },
          {
            action: "show_hide_element",
            appTarget: "",
            hoverColor: "",
            id: "hh086lza",
            onlyMode: "show",
            target: "w-oob4nyp3",
            type: "click",
          },
          {
            action: "show_hide_element",
            animationOut: null,
            appTarget: "",
            hoverColor: "",
            id: "xw2xky5b",
            onlyMode: "hide",
            target: "w-1qpgocgm",
            type: "click",
          },
          {
            action: "play_audio",
            appTarget: "",
            hoverColor: "",
            id: "owj34amy",
            target: "./Christina Perri - A Thousand Years - LatinHype (youtube).mp3",
            type: "click",
          },
          {
            action: "show_hide_element",
            appTarget: "",
            hoverColor: "",
            id: "c1r1d3ix",
            onlyMode: "hide",
            target: "w-pqtxq0p8",
            type: "click",
          },
          {
            action: "show_hide_element",
            appTarget: "",
            hoverColor: "",
            id: "g63uq34z",
            onlyMode: "show",
            target: "w-djaowtuq",
            type: "click",
          },
          {
            action: "hide_section",
            appTarget: "",
            hoverColor: "",
            id: "j3nxu9qv",
            target: null,
            type: "click",
          },
        ],
        desktop: {
          animation: {
            delay: 0,
            duration: 3,
            name: "pulse",
            repeat: "infinite",
          },
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 3,
            name: "pulse",
            repeat: "infinite",
          },
        },
        $parent: "1toiquem",
      },
      q1wlsumy: {
        type: "image-block",
        specials: {
          compressible: true,
          imageCompression: true,
          isTransparent: true,
          src: "https://statics.pancake.vn/web-media/94/28/c5/c9/8f35889fe59086f483fadc616f93739670fcefb71cc0752947effffc-w:1429-h:2000-l:177289-t:image/png.png",
        },
        id: "q1wlsumy",
        $parent: "1toiquem",
      },
      "4aeii491": {
        type: "image-block",
        specials: {
          compressible: true,
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/5a/f9/32/a3/8f426f0da03be3a183a6775045e1d4ac228140abee3751dadc3a86cb-w:1080-h:1440-l:110633-t:image/jpeg.jpg",
        },
        id: "4aeii491",
        desktop: {
          animation: { delay: 0, duration: 4, name: "slideInUp", repeat: null },
        },
        mobile: {
          animation: { delay: 0, duration: 4, name: "slideInUp", repeat: null },
        },
        $parent: "1toiquem",
      },
      bnrugie4: {
        type: "text-block",
        specials: { tag: "h2", text: "THIỆP" },
        id: "bnrugie4",
        desktop: {
          animation: {
            delay: 0,
            duration: 2,
            name: "fadeInDown",
            repeat: null,
          },
          fontSize: 26,
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 2,
            name: "fadeInDown",
            repeat: null,
          },
          fontSize: 26,
        },
        $parent: "1toiquem",
      },
      hoyb400n: {
        type: "text-block",
        specials: { tag: "h2", text: "- NHẤP VÀO THIỆP ĐỂ MỞ -" },
        id: "hoyb400n",
        desktop: { fontSize: 21 },
        mobile: { fontSize: 21 },
        $parent: "1toiquem",
      },
      dqyi2rbc: {
        type: "rectangle",
        specials: {},
        id: "dqyi2rbc",
        $parent: "1toiquem",
      },
      "3udt7eao": {
        type: "image-block",
        specials: {
          compressible: true,
          imageCompression: true,
          isTransparent: true,
          src: "https://statics.pancake.vn/web-media/ea/cc/05/c7/614dc6422e15e725e2533702e8c99c1c50c2ec42034a8cfc7a883d2f-w:1429-h:2000-l:154686-t:image/png.png",
        },
        id: "3udt7eao",
        events: [{ action: null, id: "yqm9dflc", target: null, type: "click" }],
        $parent: "1toiquem",
      },
      oob4nyp3: {
        type: "group",
        specials: {},
        id: "oob4nyp3",
        children: [
          "ohkl2lnj",
          "lfeb0egb",
          "cdlp31uy",
          "19tqxf4g",
          "wkuu9jg6",
          "s0wpujoa",
          "e7d1tx8k",
        ],
        mobile: { stickyBottom: 20 },
        $parent: "1toiquem",
      },
      ohkl2lnj: {
        type: "image-block",
        specials: {
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/32/ff/b2/30/0cb0dd13dbf17e338719a83997b3c34052a957f32af3e744b17633d2-w:100-h:100-l:4048-t:image/png.png",
        },
        id: "ohkl2lnj",
        desktop: {
          animation: { delay: 0, duration: 2, name: "zoomIn", repeat: null },
        },
        mobile: {
          animation: { delay: 0, duration: 2, name: "zoomIn", repeat: null },
        },
        $parent: "oob4nyp3",
      },
      lfeb0egb: {
        type: "text-block",
        specials: { tag: "h4", text: "Anh Tú" },
        id: "lfeb0egb",
        desktop: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInLeft",
            repeat: null,
          },
          fontSize: "35",
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInLeft",
            repeat: null,
          },
          fontSize: "35",
        },
        $parent: "oob4nyp3",
      },
      cdlp31uy: {
        type: "line",
        specials: {},
        id: "cdlp31uy",
        $parent: "oob4nyp3",
      },
      "19tqxf4g": {
        type: "text-block",
        specials: { tag: "h3", text: "31.03<br>2025<br>" },
        id: "19tqxf4g",
        desktop: {
          animation: { delay: 0, duration: 3, name: "fadeInUp", repeat: null },
          fontSize: 32,
        },
        mobile: {
          animation: { delay: 0, duration: 3, name: "fadeInUp", repeat: null },
          fontSize: 32,
        },
        $parent: "oob4nyp3",
      },
      wkuu9jg6: {
        type: "text-block",
        specials: { tag: "h4", text: "Diệu Nhi" },
        id: "wkuu9jg6",
        desktop: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInRight",
            repeat: null,
          },
          fontSize: "35",
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInRight",
            repeat: null,
          },
          fontSize: "35",
        },
        $parent: "oob4nyp3",
      },
      s0wpujoa: {
        type: "line",
        specials: {},
        id: "s0wpujoa",
        $parent: "oob4nyp3",
      },
      e7d1tx8k: {
        type: "image-block",
        specials: {
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/b3/d7/78/bb/d8759c19ffd5366a85530fbb9d84c8030baaeae14a7b2d8e6d714072-w:313-h:313-l:4969-t:image/png.png",
        },
        id: "e7d1tx8k",
        desktop: {
          animation: {
            delay: 0,
            duration: 4,
            name: "flash",
            repeat: "infinite",
          },
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 4,
            name: "flash",
            repeat: "infinite",
          },
        },
        $parent: "oob4nyp3",
      },
      np891vuj: {
        type: "image-block",
        specials: {
          compressible: true,
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/f5/9d/6e/68/68bd732f71085eb122df4674357e52a44ce50cdefc9018e1bfebbf2a-w:200-h:200-l:5929-t:image/png.png",
        },
        id: "np891vuj",
        mobile: { sticky: true, stickyBottom: 20, stickyPosition: "b-l" },
        $parent: "1toiquem",
      },
      pqtxq0p8: {
        type: "image-block",
        specials: {
          customAdvance: true,
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/02/d4/a7/88/fef5132f979892c1778a688f2039942fc24b396b332750179775f87e-w:200-h:200-l:8183-t:image/png.png",
        },
        id: "pqtxq0p8",
        events: [
          {
            action: "play_audio",
            appTarget: "",
            hoverColor: "",
            id: "on0bslwe",
            nameFile:
              "EM ĐỒNG Ý (I DO) - ĐỨC PHÚC x 911 x KHẮC HƯNG - OFFICIAL MUSIC VIDEO - VALENTINE 2023 (mp3cut.net).mp3",
            target: "./Christina Perri - A Thousand Years - LatinHype (youtube).mp3",
            type: "click",
          },
          {
            action: "show_hide_element",
            appTarget: "",
            hoverColor: "",
            id: "prwbz4w9",
            onlyMode: "hide",
            target: "w-pqtxq0p8",
            type: "click",
          },
          {
            action: "show_hide_element",
            appTarget: "",
            hoverColor: "",
            id: "7zqsovxg",
            onlyMode: "show",
            target: "w-djaowtuq",
            type: "click",
          },
        ],
        mobile: { sticky: true, stickyBottom: 20, stickyPosition: "b-l" },
        $parent: "1toiquem",
      },
      djaowtuq: {
        type: "image-block",
        specials: {
          customAdvance: true,
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/31/08/c9/52/c9f574ca2fa8481e1c8c657100583ddfbf47e33427d480a7dc32e788-w:200-h:200-l:242141-t:image/gif.gif",
        },
        id: "djaowtuq",
        events: [
          {
            action: "stop_audio",
            appTarget: "",
            hoverColor: "",
            id: "on0bslwe",
            nameFile:
              "EM ĐỒNG Ý (I DO) - ĐỨC PHÚC x 911 x KHẮC HƯNG - OFFICIAL MUSIC VIDEO - VALENTINE 2023 (mp3cut.net).mp3",
            target: "./Christina Perri - A Thousand Years - LatinHype (youtube).mp3",
            type: "click",
          },
          {
            action: "show_hide_element",
            appTarget: "",
            hoverColor: "",
            id: "prwbz4w9",
            onlyMode: "show",
            target: "w-pqtxq0p8",
            type: "click",
          },
          {
            action: "show_hide_element",
            appTarget: "",
            hoverColor: "",
            id: "f5m96fcu",
            onlyMode: "hide",
            target: "w-djaowtuq",
            type: "click",
          },
        ],
        mobile: { sticky: true, stickyBottom: 20, stickyPosition: "b-l" },
        $parent: "1toiquem",
      },
      "76hn3zct": {
        type: "image-block",
        specials: {
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/48/53/5d/e8/8360ef0daf228b537db79566ac2bfb8ff7d126e363d698bcaaf55ad8-w:100-h:100-l:4812-t:image/png.png",
        },
        id: "76hn3zct",
        events: [
          {
            action: "scroll_to",
            appTarget: "",
            hoverColor: "",
            id: "7pg6jyhd",
            target: "1toiquem",
            type: "click",
          },
        ],
        mobile: { sticky: true, stickyBottom: 20, stickyPosition: "b-r" },
        $parent: "1toiquem",
      },
      ywnx3zmg: {
        type: "image-block",
        specials: {
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/fc/e6/9f/73/869f8d1e41593a31be6fb63256122728f3320233548fdc919694c113-w:500-h:500-l:22615-t:image/png.png",
        },
        id: "ywnx3zmg",
        $parent: "1toiquem",
      },
      "1qpgocgm": {
        type: "image-block",
        specials: {
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/e7/f3/2e/9f/c37b6aa27572f1e8e9a939833d77ebe2563ed46102b316d6b293453e-w:313-h:313-l:124683-t:image/png.png",
        },
        id: "1qpgocgm",
        desktop: {
          animation: { delay: 0, duration: 2, name: "fadeInUp", repeat: null },
        },
        mobile: {
          animation: { delay: 0, duration: 2, name: "fadeInUp", repeat: null },
        },
        $parent: "1toiquem",
      },
      "40pygk87": {
        type: "image-block",
        specials: {
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/fc/e6/9f/73/869f8d1e41593a31be6fb63256122728f3320233548fdc919694c113-w:500-h:500-l:22615-t:image/png.png",
        },
        id: "40pygk87",
        $parent: "1toiquem",
      },
      "53vnzuwe": {
        type: "image-block",
        specials: {
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/01/01/53/a6/107b40fff2db3985e6374bad6eb40b8bb6dfa91f0baa5d82e0bad933-w:313-h:313-l:8578-t:image/png.png",
        },
        id: "53vnzuwe",
        $parent: "1toiquem",
      },
      hnewlzw3: {
        type: "image-block",
        specials: {
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/01/01/53/a6/107b40fff2db3985e6374bad6eb40b8bb6dfa91f0baa5d82e0bad933-w:313-h:313-l:8578-t:image/png.png",
        },
        id: "hnewlzw3",
        $parent: "1toiquem",
      },
      "9r8tifvf": {
        type: "button",
        specials: { text: "THIỆP CƯỚI ONLINE LONG THỊNH" },
        id: "9r8tifvf",
        desktop: { fontSize: 17 },
        mobile: {
          sticky: true,
          stickyBottom: 20,
          stickyPosition: "flex",
          stickyTop: 20,
          fontSize: 17,
        },
        $parent: "1toiquem",
      },
      "28wd2jg4": {
        type: "section",
        specials: { imageCompression: true },
        id: "28wd2jg4",
        children: [
          "8kjibpmq",
          "3hbjzhq6",
          "wlk3yclm",
          "gksl9w4l",
          "91jxhp0m",
          "ig5jcswu",
          "j8n1a9zw",
          "2hyi8ra3",
          "bv74resi",
          "32etj2r3",
          "6i7xa1kt",
          "giudke9b",
          "ioujowzg",
          "hs9njuu7",
          "yjsm9xd2",
          "1u5rhi6o",
          "dh2fdsr6",
          "1vrm5g0n",
        ],
      },
      "8kjibpmq": {
        type: "line",
        specials: {},
        id: "8kjibpmq",
        $parent: "28wd2jg4",
      },
      "3hbjzhq6": {
        type: "text-block",
        specials: { tag: "h2", text: "Thư<br>Mời<br>Cưới<br>" },
        id: "3hbjzhq6",
        desktop: {
          animation: {
            delay: 0,
            duration: 2,
            name: "fadeInRight",
            repeat: null,
          },
          fontSize: 26,
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 2,
            name: "fadeInRight",
            repeat: null,
          },
          fontSize: 26,
        },
        $parent: "28wd2jg4",
      },
      wlk3yclm: {
        type: "line",
        specials: {},
        id: "wlk3yclm",
        $parent: "28wd2jg4",
      },
      gksl9w4l: {
        type: "text-block",
        specials: { tag: "p", text: "NHÀ TRAI<br>" },
        id: "gksl9w4l",
        desktop: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInRight",
            repeat: null,
          },
          fontSize: 16,
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInRight",
            repeat: null,
          },
          fontSize: 16,
        },
        $parent: "28wd2jg4",
      },
      "91jxhp0m": {
        type: "text-block",
        specials: { tag: "p", text: "Quận 8, Hồ Chí Minh" },
        id: "91jxhp0m",
        desktop: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInRight",
            repeat: null,
          },
          fontSize: 13,
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInRight",
            repeat: null,
          },
          fontSize: 13,
        },
        $parent: "28wd2jg4",
      },
      ig5jcswu: {
        type: "text-block",
        specials: {
          tag: "p",
          text: "ÔNG CẤN VĂN AN\n<br>BÀ NGUYỄN THỊ HẢI<br>",
        },
        id: "ig5jcswu",
        desktop: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInRight",
            repeat: null,
          },
          fontSize: 16,
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInRight",
            repeat: null,
          },
          fontSize: 16,
        },
        $parent: "28wd2jg4",
      },
      j8n1a9zw: {
        type: "text-block",
        specials: { tag: "p", text: "NHÀ GÁI<br>" },
        id: "j8n1a9zw",
        desktop: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInRight",
            repeat: null,
          },
          fontSize: 16,
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInRight",
            repeat: null,
          },
          fontSize: 16,
        },
        $parent: "28wd2jg4",
      },
      "2hyi8ra3": {
        type: "text-block",
        specials: { tag: "p", text: "Quận 8, Hồ Chí Minh" },
        id: "2hyi8ra3",
        desktop: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInRight",
            repeat: null,
          },
          fontSize: 13,
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInRight",
            repeat: null,
          },
          fontSize: 13,
        },
        $parent: "28wd2jg4",
      },
      bv74resi: {
        type: "text-block",
        specials: {
          tag: "p",
          text: "ÔNG CẤN VĂN AN\n<br>BÀ NGUYỄN THỊ HẢI<br>",
        },
        id: "bv74resi",
        desktop: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInRight",
            repeat: null,
          },
          fontSize: 16,
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInRight",
            repeat: null,
          },
          fontSize: 16,
        },
        $parent: "28wd2jg4",
      },
      "32etj2r3": {
        type: "text-block",
        specials: {
          tag: "h2",
          text: "Trân Trọng Báo Tin Lễ Thành Hôn Của<br>",
        },
        id: "32etj2r3",
        desktop: {
          animation: { delay: 0, duration: 3, name: "fadeInUp", repeat: null },
          fontSize: "20",
        },
        mobile: {
          animation: { delay: 0, duration: 3, name: "fadeInUp", repeat: null },
          fontSize: "20",
        },
        $parent: "28wd2jg4",
      },
      "6i7xa1kt": {
        type: "text-block",
        specials: { tag: "h1", text: "Nguyễn Anh Tú" },
        id: "6i7xa1kt",
        desktop: {
          animation: { delay: 0, duration: 4, name: "zoomIn", repeat: null },
          fontSize: 40,
        },
        mobile: {
          animation: { delay: 0, duration: 4, name: "zoomIn", repeat: null },
          fontSize: 40,
        },
        $parent: "28wd2jg4",
      },
      giudke9b: {
        type: "text-block",
        specials: { tag: "h1", text: "Trần Diệu Nhi" },
        id: "giudke9b",
        desktop: {
          animation: { delay: 0, duration: 4, name: "zoomIn", repeat: null },
          fontSize: 40,
        },
        mobile: {
          animation: { delay: 0, duration: 4, name: "zoomIn", repeat: null },
          fontSize: 40,
        },
        $parent: "28wd2jg4",
      },
      ioujowzg: {
        type: "text-block",
        specials: { tag: "h1", text: "&amp;" },
        id: "ioujowzg",
        desktop: {
          animation: { delay: 0, duration: 4, name: "zoomIn", repeat: null },
          fontSize: 40,
        },
        mobile: {
          animation: { delay: 0, duration: 4, name: "zoomIn", repeat: null },
          fontSize: 40,
        },
        $parent: "28wd2jg4",
      },
      hs9njuu7: {
        type: "image-block",
        specials: {
          compressible: true,
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/2c/43/3a/9b/d51e27bb45829b83e91ea54e82189178515342122ad7d4bf856d30c1-w:1080-h:720-l:53311-t:image/jpeg.jpg",
        },
        id: "hs9njuu7",
        desktop: {
          animation: { delay: 0, duration: 3, name: "slideInUp", repeat: null },
        },
        mobile: {
          animation: { delay: 0, duration: 3, name: "slideInUp", repeat: null },
        },
        $parent: "28wd2jg4",
      },
      yjsm9xd2: {
        type: "rectangle",
        specials: {},
        id: "yjsm9xd2",
        $parent: "28wd2jg4",
      },
      "1u5rhi6o": {
        type: "image-block",
        specials: {
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/1f/94/22/d2/4b84947380d319a034d00e7f832c3382c2e560af38d2eb0c27f28233-w:313-h:313-l:4199-t:image/png.png",
        },
        id: "1u5rhi6o",
        desktop: {
          animation: { delay: 0, duration: 2, name: "fadeInUp", repeat: null },
        },
        mobile: {
          animation: { delay: 0, duration: 2, name: "fadeInUp", repeat: null },
        },
        $parent: "28wd2jg4",
      },
      dh2fdsr6: {
        type: "rectangle",
        specials: {},
        id: "dh2fdsr6",
        $parent: "28wd2jg4",
      },
      "1vrm5g0n": {
        type: "image-block",
        specials: {
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/57/9d/b4/54/8062abb209fa7d1a4f616d71addf48e4b528644d159a733f58090902-w:100-h:100-l:7010-t:image/png.png",
        },
        id: "1vrm5g0n",
        $parent: "28wd2jg4",
      },
      u2qdu5go: {
        type: "section",
        specials: { imageCompression: true },
        id: "u2qdu5go",
        children: [
          "amfdze1w",
          "trta43bz",
          "pdl931a6",
          "k8kl83qy",
          "kbgnz2rp",
          "s2av0vl0",
          "bifzmam8",
          "6amly90s",
          "rvjhix10",
          "0m3cmvaa",
          "2z4vbngp",
          "xd4gq2s2",
          "p4gatvnw",
        ],
      },
      amfdze1w: {
        type: "text-block",
        specials: { tag: "h2", text: "Trân Trọng Kính Mời<br>" },
        id: "amfdze1w",
        desktop: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInLeft",
            repeat: null,
          },
          fontSize: 25,
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInLeft",
            repeat: null,
          },
          fontSize: 25,
        },
        $parent: "u2qdu5go",
      },
      trta43bz: {
        type: "text-block",
        specials: { tag: "p", text: "(Tức Ngày 02 Tháng 03 Năm Ất Tỵ)<br>" },
        id: "trta43bz",
        desktop: {
          animation: { delay: 0, duration: 2, name: "fadeInUp", repeat: null },
          fontSize: 14,
        },
        mobile: {
          animation: { delay: 0, duration: 2, name: "fadeInUp", repeat: null },
          fontSize: 14,
        },
        $parent: "u2qdu5go",
      },
      pdl931a6: {
        type: "text-block",
        specials: { tag: "p", text: "Tại The ADORA Center" },
        id: "pdl931a6",
        desktop: {
          animation: { delay: 0, duration: 3, name: "fadeInUp", repeat: null },
          fontSize: 17,
        },
        mobile: {
          animation: { delay: 0, duration: 2, name: "zoomIn", repeat: null },
          fontSize: 17,
        },
        $parent: "u2qdu5go",
      },
      k8kl83qy: {
        type: "text-block",
        specials: {
          tag: "p",
          text: '<span style="font-weight: bold;">Tháng 03</span><br>',
        },
        id: "k8kl83qy",
        desktop: { fontSize: 14 },
        mobile: {
          animation: {
            delay: 0,
            duration: 2,
            name: "fadeInLeft",
            repeat: null,
          },
          fontSize: 14,
        },
        $parent: "u2qdu5go",
      },
      kbgnz2rp: {
        type: "text-block",
        specials: { tag: "p", text: "2025<br>" },
        id: "kbgnz2rp",
        desktop: { fontSize: 14 },
        mobile: {
          animation: {
            delay: 0,
            duration: 2,
            name: "fadeInRight",
            repeat: null,
          },
          fontSize: 14,
        },
        $parent: "u2qdu5go",
      },
      s2av0vl0: {
        type: "line",
        specials: {},
        id: "s2av0vl0",
        mobile: {
          animation: { delay: 0, duration: 2, name: "fadeIn", repeat: null },
        },
        $parent: "u2qdu5go",
      },
      bifzmam8: {
        type: "line",
        specials: {},
        id: "bifzmam8",
        mobile: {
          animation: { delay: 0, duration: 2, name: "fadeIn", repeat: null },
        },
        $parent: "u2qdu5go",
      },
      "6amly90s": {
        type: "text-block",
        specials: {
          tag: "p",
          text: '<span style="font-weight: bold;">TIỆC MỪNG LỄ THÀNH HÔN</span>',
        },
        id: "6amly90s",
        desktop: {
          animation: {
            delay: 0,
            duration: 2,
            name: "fadeInDown",
            repeat: null,
          },
          fontSize: 14,
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 2,
            name: "fadeInDown",
            repeat: null,
          },
          fontSize: 14,
        },
        $parent: "u2qdu5go",
      },
      rvjhix10: {
        type: "text-block",
        specials: { tag: "p", text: "Vào Lúc 10h00 | Thứ 6" },
        id: "rvjhix10",
        desktop: { fontSize: 14 },
        mobile: {
          animation: { delay: 0, duration: 2, name: "fadeInUp", repeat: null },
          fontSize: 14,
        },
        $parent: "u2qdu5go",
      },
      "0m3cmvaa": {
        type: "text-block",
        specials: { tag: "p", text: "30<br>" },
        id: "0m3cmvaa",
        desktop: { fontSize: 14 },
        mobile: {
          animation: { delay: 0, duration: 2, name: "zoomIn", repeat: null },
          fontSize: 42,
        },
        $parent: "u2qdu5go",
      },
      "2z4vbngp": {
        type: "image-block",
        specials: {
          compressible: true,
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/21/54/83/cb/163b4872b6600196d0ac068b1f046c5dd5f9d20c3ddad5e7c0abea9b-w:736-h:980-l:48194-t:image/jpeg.jfif",
        },
        id: "2z4vbngp",
        desktop: {
          animation: { delay: 0, duration: 3, name: "fadeInUp", repeat: null },
        },
        mobile: {
          animation: { delay: 0, duration: 3, name: "fadeInUp", repeat: null },
        },
        $parent: "u2qdu5go",
      },
      xd4gq2s2: {
        type: "image-block",
        specials: {
          compressible: true,
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/3c/3b/ca/e1/e12ca0e6af675d653327f5a3b5d2c7c2385f71d26b8fee7604b45828-w:1706-h:2560-l:224512-t:image/jpeg.jpg",
        },
        id: "xd4gq2s2",
        desktop: {
          animation: { delay: 0, duration: 3, name: "fadeInUp", repeat: null },
        },
        mobile: {
          animation: { delay: 0, duration: 3, name: "fadeInUp", repeat: null },
        },
        $parent: "u2qdu5go",
      },
      p4gatvnw: {
        type: "image-block",
        specials: {
          compressible: true,
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/6f/2b/71/1d/03a457a718b5bf78c5639d6de0521b7a19ec698dcd5737408a50bd16-w:1707-h:2560-l:275640-t:image/jpeg.jpg",
        },
        id: "p4gatvnw",
        desktop: {
          animation: { delay: 0, duration: 3, name: "fadeInUp", repeat: null },
        },
        mobile: {
          animation: { delay: 0, duration: 3, name: "fadeInUp", repeat: null },
        },
        $parent: "u2qdu5go",
      },
      frfn2a1z: {
        type: "section",
        specials: { imageCompression: true },
        id: "frfn2a1z",
        children: ["3m9ley3f", "q5ac8dqm"],
      },
      "3m9ley3f": {
        type: "image-block",
        specials: {
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/29/ab/24/07/41f1ee19c5cec59b346d0318a574a667b9aae0c06afc8a82c04a3c46-w:2400-h:2400-l:103598-t:image/png.png",
        },
        id: "3m9ley3f",
        desktop: {
          animation: { delay: 0, duration: 2, name: "fadeIn", repeat: null },
        },
        mobile: {
          animation: { delay: 0, duration: 2, name: "fadeIn", repeat: null },
        },
        $parent: "frfn2a1z",
      },
      q5ac8dqm: {
        type: "image-block",
        specials: {
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/59/9d/0d/23/829a2a25903e5b03a029f62911ad0300b2c875df84e143b3258f9633-w:3600-h:3600-l:165926-t:image/png.png",
        },
        id: "q5ac8dqm",
        desktop: {
          animation: {
            delay: 0,
            duration: 2,
            name: "pulse",
            repeat: "infinite",
          },
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 2,
            name: "pulse",
            repeat: "infinite",
          },
        },
        $parent: "frfn2a1z",
      },
      gxpbejzi: {
        type: "section",
        specials: { imageCompression: true },
        id: "gxpbejzi",
        children: [
          "b8ao84la",
          "8799m2jd",
          "i7ym6cbi",
          "4y6khmrv",
          "m1kk35d9",
          "gpi1okjt",
          "t2sokzzh",
          "sr1oja6m",
        ],
      },
      b8ao84la: {
        type: "text-block",
        specials: {
          tag: "p",
          text: "xxx, Phường xxx, Quận xxx,<br>Hồ Chí Minh<br>",
        },
        id: "b8ao84la",
        desktop: {
          animation: { delay: 0, duration: 2, name: "fadeInUp", repeat: null },
          fontSize: 14,
        },
        mobile: {
          animation: { delay: 0, duration: 2, name: "fadeInUp", repeat: null },
          fontSize: 14,
        },
        $parent: "gxpbejzi",
      },
      "8799m2jd": {
        type: "text-block",
        specials: {
          tag: "p",
          text: '<span style="font-weight: 700;">The ADORA Center</span><br>',
        },
        id: "8799m2jd",
        desktop: {
          animation: { delay: 0, duration: 2, name: "fadeInUp", repeat: null },
          fontSize: 18,
        },
        mobile: {
          animation: { delay: 0, duration: 2, name: "fadeInUp", repeat: null },
          fontSize: 18,
        },
        $parent: "gxpbejzi",
      },
      i7ym6cbi: {
        type: "button",
        specials: { text: "Xem Chỉ Đường" },
        id: "i7ym6cbi",
        events: [
          {
            action: "open_link",
            appTarget: "",
            hoverColor: "",
            id: "11z1nlck",
            target: "https://maps.app.goo.gl/dEf8jaWbEzp1hcxi6",
            type: "click",
          },
          {
            action: "animation_hover",
            animationHover: "scale",
            appTarget: "",
            hoverColor: "",
            id: "v7zrrz21",
            target: null,
            type: "hover",
          },
        ],
        desktop: {
          animation: { delay: 0, duration: 2, name: "fadeInUp", repeat: "1" },
          fontSize: 15,
        },
        mobile: {
          animation: { delay: 0, duration: 2, name: "fadeInUp", repeat: "1" },
          fontSize: 15,
        },
        $parent: "gxpbejzi",
      },
      "4y6khmrv": {
        type: "rectangle",
        specials: {},
        id: "4y6khmrv",
        $parent: "gxpbejzi",
      },
      m1kk35d9: {
        type: "html-box",
        specials: {
          html: '&lt;iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2943.804837748019!2d105.83118377400844!3d21.008011088493312!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135ac7f46b516ef%3A0x4b8dcd20d6d7f980!2zTmjDoCBow6BuZyBUaeG7h2MgY8aw4bubaSBYYW5oIFBhbGFjZQ!5e1!3m2!1svi!2s!4v1762855102779!5m2!1svi!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"&gt;&lt;/iframe&gt;',
        },
        id: "m1kk35d9",
        $parent: "gxpbejzi",
      },
      gpi1okjt: {
        type: "rectangle",
        specials: {},
        id: "gpi1okjt",
        $parent: "gxpbejzi",
      },
      t2sokzzh: {
        type: "image-block",
        specials: {
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/ea/22/0a/29/7282a3145204e1bfd9fcd61e814d26ec7b304aece5149f90e6438404-w:313-h:313-l:10169-t:image/png.png",
        },
        id: "t2sokzzh",
        desktop: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInLeft",
            repeat: null,
          },
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInLeft",
            repeat: null,
          },
        },
        $parent: "gxpbejzi",
      },
      sr1oja6m: {
        type: "text-block",
        specials: { tag: "h2", text: "Địa Điểm Tổ Chức<br>" },
        id: "sr1oja6m",
        desktop: {
          animation: {
            delay: 0,
            duration: 2,
            name: "fadeInLeft",
            repeat: null,
          },
          fontSize: 26,
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 2,
            name: "fadeInLeft",
            repeat: null,
          },
          fontSize: 26,
        },
        $parent: "gxpbejzi",
      },
      "7mhdm53u": {
        type: "section",
        specials: { imageCompression: true },
        id: "7mhdm53u",
        children: ["3yfyeul6", "hxsmv8a3", "n9eye9rx1", "n9eye9rx", "hl53suyf"],
      },
      "3yfyeul6": {
        type: "rectangle",
        specials: {},
        id: "3yfyeul6",
        $parent: "7mhdm53u",
      },
      hxsmv8a3: {
        type: "text-block",
        specials: {
          tag: "h2",
          text: "Xác Nhận Tham Dự<br>&amp;<br>Gửi Lời Chúc<br>",
        },
        id: "hxsmv8a3",
        desktop: {
          animation: {
            delay: 0,
            duration: 1,
            name: "fadeInRight",
            repeat: null,
          },
          fontSize: "25",
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 1,
            name: "fadeInRight",
            repeat: null,
          },
          fontSize: "25",
        },
        $parent: "7mhdm53u",
      },
      n9eye9rx: {
        type: "button",
        specials: { closePopupOther: true, text: "GỬI MỪNG CƯỚI" },
        id: "n9eye9rx",
        events: [
          {
            action: "open_popup",
            appTarget: "",
            hoverColor: "",
            id: "kbygmywh",
            target: "g81yux0n",
            type: "click",
          },
          {
            action: "animation_hover",
            animationHover: "scale",
            appTarget: "",
            hoverColor: "",
            id: "0ucb48i5",
            target: null,
            type: "hover",
          },
        ],
        desktop: { fontSize: "16" },
        mobile: { fontSize: "16" },
        $parent: "7mhdm53u",
      },
      n9eye9rx1: {
        type: "button",
        specials: { closePopupOther: true, text: "GỬI MỪNG CƯỚI" },
        id: "n9eye9rx1",
        events: [
          {
            action: "open_popup",
            appTarget: "",
            hoverColor: "",
            id: "kbygmywh1",
            target: "g81yux0n1",
            type: "click",
          },
          {
            action: "animation_hover",
            animationHover: "scale",
            appTarget: "",
            hoverColor: "",
            id: "0ucb48i5",
            target: null,
            type: "hover",
          },
        ],
        desktop: { fontSize: "16" },
        mobile: { fontSize: "16" },
        $parent: "7mhdm53u",
      },
      hl53suyf: {
        type: "form",
        id: "hl53suyf",
        specials: {
          closePopupOther: true,
          customAdvance: false,
          customArrangementSheet: true,
          fb_conversion_value: "10000",
          fb_event_type: "CompleteRegistration",
          fb_tracking_currency: "VND",
          multiForm: false,
          multiFormParent: "",
          partnerServiceId: 139372,
        },
        children: ["unj9ai75", "klql4ysp", "m1wmtbcv", "9du0r7g4", "8h31rtp3"],
        desktop: { fontSize: 13 },
        mobile: { fontSize: 13 },
        $parent: "7mhdm53u",
      },
      unj9ai75: {
        type: "input",
        specials: {
          field_name: "full_name",
          field_placeholder: "Tên của bạn là?",
          required: true,
        },
        id: "unj9ai75",
        $parent: "hl53suyf",
      },
      klql4ysp: {
        type: "button",
        specials: { text: "GỬI NGAY" },
        id: "klql4ysp",
        events: [
          {
            action: "animation_hover",
            id: "u04qjdqi",
            target: null,
            type: "hover",
          },
        ],
        desktop: { fontSize: 14 },
        mobile: { fontSize: 16 },
        $parent: "hl53suyf",
      },
      m1wmtbcv: {
        type: "input",
        specials: {
          field_name: "text_input_1",
          field_placeholder: "Bạn là gì của Dâu Rể nhỉ?",
        },
        id: "m1wmtbcv",
        $parent: "hl53suyf",
      },
      "9du0r7g4": {
        type: "input",
        specials: {
          field_name: "text_input_2",
          field_placeholder: "Gửi lời chúc đến Dâu Rể nhé!",
        },
        id: "9du0r7g4",
        $parent: "hl53suyf",
      },
      "8h31rtp3": {
        type: "select",
        specials: {
          field_name: "select_1",
          field_placeholder: "Bạn Có Tham Dự Không?",
          options: [
            { id: "00a1lsp9", name: "Có Thể Tham Dự", value: "untitled" },
            { id: "qfzou631", name: "Không Thể Tham Dự", value: "untitled" },
          ],
          required: true,
        },
        id: "8h31rtp3",
        $parent: "hl53suyf",
      },
      pniputpo: {
        type: "section",
        specials: { imageCompression: true },
        id: "pniputpo",
        children: [
          "i9mk0qdo",
          "6m7phoby",
          "7m08afme",
          "gfr8kgrk",
          "ytqzomid",
          "6klqgubq",
        ],
      },
      i9mk0qdo: {
        type: "image-block",
        specials: {
          compressible: true,
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/1f/ec/67/de/9e0ddf95bd1e8508eb6f0177f5ef50605c83a3a9833c96b0e66ad619-w:1080-h:1620-l:309623-t:image/jpeg.jpg",
        },
        id: "i9mk0qdo",
        desktop: {
          animation: { delay: 0, duration: 3, name: "zoomIn", repeat: null },
        },
        mobile: {
          animation: { delay: 0, duration: 3, name: "zoomIn", repeat: null },
        },
        $parent: "pniputpo",
      },
      "6m7phoby": {
        type: "image-block",
        specials: {
          compressible: true,
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/4e/3a/ee/02/dc987c839e2d2b41608056aca76c61f8069679c0fdf6b585b28e0267-w:1080-h:1620-l:290935-t:image/jpeg.jpg",
        },
        id: "6m7phoby",
        desktop: {
          animation: { delay: 0, duration: 3, name: "zoomIn", repeat: null },
        },
        mobile: {
          animation: { delay: 0, duration: 3, name: "zoomIn", repeat: null },
        },
        $parent: "pniputpo",
      },
      "7m08afme": {
        type: "image-block",
        specials: {
          compressible: true,
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/10/8a/c7/a3/4469b23a30640d824081431e33cfd219c78e0717425798aed85f1535-w:1080-h:1440-l:167192-t:image/jpeg.jpg",
        },
        id: "7m08afme",
        desktop: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInLeft",
            repeat: null,
          },
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInLeft",
            repeat: null,
          },
        },
        $parent: "pniputpo",
      },
      gfr8kgrk: {
        type: "image-block",
        specials: {
          compressible: true,
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/ba/87/8e/98/5b47f056d251a6b8bb4861fe26e96bff44e06e4543af717b5d2d8b23-w:1080-h:1440-l:133756-t:image/jpeg.jpg",
        },
        id: "gfr8kgrk",
        desktop: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInRight",
            repeat: null,
          },
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInRight",
            repeat: null,
          },
        },
        $parent: "pniputpo",
      },
      ytqzomid: {
        type: "text-block",
        specials: { tag: "p", text: "Album hình cưới" },
        id: "ytqzomid",
        desktop: {
          animation: { delay: 0, duration: 3, name: "fadeInUp", repeat: null },
          fontSize: 28,
        },
        mobile: {
          animation: { delay: 0, duration: 2, name: "zoomIn", repeat: null },
          fontSize: 32,
        },
        $parent: "pniputpo",
      },
      "6klqgubq": {
        type: "image-block",
        specials: {
          compressible: true,
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/46/45/b6/42/7ebe591a302e052c877665786914eac1192398f4f8181152f26761fd-w:1080-h:1620-l:360585-t:image/jpeg.jpg",
        },
        id: "6klqgubq",
        desktop: {
          animation: { delay: 0, duration: 3, name: "zoomIn", repeat: null },
        },
        mobile: {
          animation: { delay: 0, duration: 3, name: "zoomIn", repeat: null },
        },
        $parent: "pniputpo",
      },
      atb1tsrv: {
        type: "section",
        specials: { imageCompression: true },
        id: "atb1tsrv",
        children: ["07ds8l4t", "atvsanei", "6zk6tjag"],
      },
      "07ds8l4t": {
        type: "image-block",
        specials: {
          compressible: true,
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/df/28/0d/67/a2aecb446deb980a1709b1c3f2828a03a43952e40b2c5b76a57641cf-w:1080-h:1440-l:125280-t:image/jpeg.jpg",
        },
        id: "07ds8l4t",
        desktop: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInLeft",
            repeat: null,
          },
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInLeft",
            repeat: null,
          },
        },
        $parent: "atb1tsrv",
      },
      atvsanei: {
        type: "image-block",
        specials: {
          compressible: true,
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/60/b1/5e/e9/89fd2d2d6cd9a62db6e70776243eb9ed8603fc1fb415bdc95da92104-w:1286-h:857-l:255701-t:image/jpeg.jpg",
        },
        id: "atvsanei",
        desktop: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInRight",
            repeat: null,
          },
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInRight",
            repeat: null,
          },
        },
        $parent: "atb1tsrv",
      },
      "6zk6tjag": {
        type: "image-block",
        specials: {
          compressible: true,
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/7a/e8/d6/f6/da197a5a3542dfe09e7faa9e118999103385582808a2e2014fc72986-w:1286-h:988-l:154700-t:image/jpeg.jpg",
        },
        id: "6zk6tjag",
        mobile: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInRight",
            repeat: null,
          },
        },
        $parent: "atb1tsrv",
      },
      tpklluth: {
        type: "section",
        specials: { imageCompression: true },
        id: "tpklluth",
        children: ["qg9pg53z", "3i6z5fev"],
      },
      qg9pg53z: {
        type: "image-block",
        specials: {
          compressible: true,
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/50/b1/a5/b8/1b155f57e57ad9a1a81d973470e98ff4e9bd15d0eae0a678e86431f7-w:1079-h:1436-l:181431-t:image/jpeg.jpg",
        },
        id: "qg9pg53z",
        desktop: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInLeft",
            repeat: null,
          },
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInLeft",
            repeat: null,
          },
        },
        $parent: "tpklluth",
      },
      "3i6z5fev": {
        type: "image-block",
        specials: {
          compressible: true,
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/6b/4d/33/b6/41e9ee049b1a0b0fb616d8599fa0e05dafb8c9fdc1d533cef1ffe1f8-w:1079-h:1434-l:200906-t:image/jpeg.jpg",
        },
        id: "3i6z5fev",
        desktop: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInRight",
            repeat: null,
          },
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 3,
            name: "fadeInRight",
            repeat: null,
          },
        },
        $parent: "tpklluth",
      },
      "1kaa9b1v": {
        type: "section",
        specials: { imageCompression: true },
        id: "1kaa9b1v",
        children: ["sj86rf1m", "pvtvxy0x", "iylwpged", "ihlyqwez"],
      },
      sj86rf1m: {
        type: "image-block",
        specials: {
          compressible: true,
          imageCompression: true,
          isTransparent: false,
          src: "https://statics.pancake.vn/web-media/b8/a9/be/33/645ec95fdf293c645381a4aefd65aada76ac2c12e1a08201bf323dd5-w:1919-h:2560-l:363265-t:image/jpeg.jpg",
        },
        id: "sj86rf1m",
        $parent: "1kaa9b1v",
      },
      pvtvxy0x: {
        type: "rectangle",
        specials: {},
        id: "pvtvxy0x",
        $parent: "1kaa9b1v",
      },
      iylwpged: {
        type: "image-block",
        specials: {
          compressible: true,
          imageCompression: true,
          isTransparent: true,
          src: "https://statics.pancake.vn/web-media/cf/cf/28/5f/f9ca08165577556ed2df053b0962a0e8e670490844d7ad5e84fa48b2-w:1366-h:530-l:48754-t:image/png.png",
        },
        id: "iylwpged",
        desktop: {
          animation: {
            delay: 0,
            duration: 3,
            name: "pulse",
            repeat: "infinite",
          },
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 3,
            name: "pulse",
            repeat: "infinite",
          },
        },
        $parent: "1kaa9b1v",
      },
      ihlyqwez: {
        type: "text-block",
        specials: { tag: "p", text: "Rất hân hạnh được đón tiếp!" },
        id: "ihlyqwez",
        desktop: {
          animation: { delay: 0, duration: 3, name: "fadeInUp", repeat: null },
          fontSize: 38,
        },
        mobile: {
          animation: { delay: 0, duration: 3, name: "fadeInUp", repeat: null },
          fontSize: 38,
        },
        $parent: "1kaa9b1v",
      },
      fgek8m28: {
        type: "section",
        specials: { imageCompression: true },
        id: "fgek8m28",
        children: ["iptyd1uk"],
      },
      iptyd1uk: {
        type: "group",
        specials: {},
        id: "iptyd1uk",
        children: [
          "1f5kx0xs",
          "lqaf2v0z",
          "79dh2iym",
          "hmtd6z2n",
          "0hjz1zes",
          "ajvubs7y",
        ],
        $parent: "fgek8m28",
      },
      "1f5kx0xs": {
        type: "text-block",
        specials: { tag: "h1", text: "| THIỆP CƯỚI ONLINE LONG THỊNH" },
        id: "1f5kx0xs",
        desktop: { fontSize: 15 },
        mobile: { fontSize: 15 },
        $parent: "iptyd1uk",
      },
      lqaf2v0z: {
        type: "rectangle",
        specials: {
          sample: "social-logo",
          src: 'center center/ cover no-repeat  content-box url("https://content.pancake.vn/1/be/ad/61/25/69ccff4bf9c533a8297ad940b8f871b8bc7057593d2ec6f7d9c9066b.png") border-box',
        },
        id: "lqaf2v0z",
        $parent: "iptyd1uk",
      },
      "79dh2iym": {
        type: "rectangle",
        specials: {
          sample: "social-logo",
          src: "https://statics.pancake.vn/web-media/36/b3/ec/ae/eb9548e74deddff898a48c5caa4791b84669476bafc00e5c1704e002-w:980-h:980-l:7525-t:image/webp.webp",
        },
        id: "79dh2iym",
        $parent: "iptyd1uk",
      },
      hmtd6z2n: {
        type: "rectangle",
        specials: {
          sample: "social-logo",
          src: 'center center/ cover no-repeat  content-box url("https://content.pancake.vn/1/08/3f/7a/e9/be9a053a77ec7cdb461246a62779525962247b7146d4dcccce9c1cfb.png") border-box',
        },
        id: "hmtd6z2n",
        $parent: "iptyd1uk",
      },
      "0hjz1zes": {
        type: "line",
        specials: {},
        id: "0hjz1zes",
        $parent: "iptyd1uk",
      },
      ajvubs7y: {
        type: "rectangle",
        specials: {},
        id: "ajvubs7y",
        events: [
          {
            action: "open_link",
            appTarget: "",
            hoverColor: "",
            id: "b2v4gn6g",
            target: "https://www.ewedinvite.site/info",
            type: "click",
          },
        ],
        $parent: "iptyd1uk",
      },
      __popup_default__: {
        type: "popup",
        specials: {
          src: "https://statics.pancake.vn/web-media/16/9e/a4/ac/762f2d7becdeecc1d0ebaa1eda69eff9d1e3c531d99eca87e1781fcc-w:1079-h:1441-l:202842-t:image/jpeg.jpg",
        },
        id: "__popup_default__",
        children: ["au0o7yap", "766uvdhg", "zbmg6glj", "ogbk63vj"],
      },
      au0o7yap: {
        type: "rectangle",
        specials: {},
        id: "au0o7yap",
        events: [
          {
            action: "close_popup",
            id: "t3jgjr2t",
            target: "__popup_default__",
            type: "click",
          },
        ],
        $parent: "__popup_default__",
      },
      "766uvdhg": {
        type: "rectangle",
        specials: {},
        id: "766uvdhg",
        $parent: "__popup_default__",
      },
      zbmg6glj: {
        type: "image-block",
        specials: {
          compressible: true,
          imageCompression: true,
          isTransparent: true,
          src: "https://statics.pancake.vn/web-media/cf/cf/28/5f/f9ca08165577556ed2df053b0962a0e8e670490844d7ad5e84fa48b2.png",
        },
        id: "zbmg6glj",
        desktop: {
          animation: {
            delay: 0,
            duration: 3,
            name: "pulse",
            repeat: "infinite",
          },
        },
        mobile: {
          animation: {
            delay: 0,
            duration: 3,
            name: "pulse",
            repeat: "infinite",
          },
        },
        $parent: "__popup_default__",
      },
      ogbk63vj: {
        type: "text-block",
        specials: { tag: "p", text: "Rất hân hạnh được đón tiếp!" },
        id: "ogbk63vj",
        desktop: {
          animation: { delay: 0, duration: 3, name: "fadeInUp", repeat: null },
          fontSize: 38,
        },
        mobile: {
          animation: { delay: 0, duration: 3, name: "fadeInUp", repeat: null },
          fontSize: 38,
        },
        $parent: "__popup_default__",
      },
      g81yux0n: {
        type: "popup",
        specials: {
          src: "https://statics.pancake.vn/web-media/7a/7a/9b/e6/503fcb9cda6afe643293024cb66fe4a8fd7296f58e3b762f84f1f463.jpg",
        },
        id: "g81yux0n",
        children: ["it5xx3wr", "w7jquvg1", "oqnvrkg3", "p8etkpq1", "k0vu3e5e"],
      },
      it5xx3wr: {
        type: "rectangle",
        specials: {},
        id: "it5xx3wr",
        $parent: "g81yux0n",
      },
      w7jquvg1: {
        type: "rectangle",
        specials: {},
        id: "w7jquvg1",
        events: [
          {
            action: "close_popup",
            id: "t3jgjr2z",
            target: "g81yux0n",
            type: "click",
          },
        ],
        $parent: "g81yux0n",
      },
      oqnvrkg3: {
        type: "text-block",
        specials: { tag: "h2", text: "Gửi Mừng Cưới" },
        id: "oqnvrkg3",
        desktop: {
          animation: { delay: 0, duration: 2, name: "fadeInUp", repeat: null },
          fontSize: "22",
        },
        mobile: { fontSize: 40 },
        $parent: "g81yux0n",
      },
      p8etkpq1: {
        type: "image-block",
        specials: {
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/e2/bc/35/38/dc2d9ddf74d997785eb0c802bd3237a50de1118e505f1e0a89ae4ec1-w:592-h:1280-l:497233-t:image/png.png",
        },
        id: "p8etkpq1",
        $parent: "g81yux0n",
      },
      k0vu3e5e: {
        type: "text-block",
        specials: {
          tag: "h4",
          text: "MBBANK - NGUYEN TAN DAT<br>8838683860<br>",
        },
        id: "k0vu3e5e",
        desktop: { fontSize: 17 },
        mobile: { fontSize: 17 },
        $parent: "g81yux0n",
      },

      g81yux0n1: {
        type: "popup",
        specials: {
          src: "https://statics.pancake.vn/web-media/7a/7a/9b/e6/503fcb9cda6afe643293024cb66fe4a8fd7296f58e3b762f84f1f463.jpg",
        },
        id: "g81yux0n1",
        children: [
          "it5xx3wr1",
          "w7jquvg11",
          "oqnvrkg31",
          "p8etkpq11",
          "k0vu3e5e1",
        ],
      },
      it5xx3wr1: {
        type: "rectangle",
        specials: {},
        id: "it5xx3wr1",
        $parent: "g81yux0n1",
      },
      w7jquvg11: {
        type: "rectangle",
        specials: {},
        id: "w7jquvg11",
        events: [
          {
            action: "close_popup",
            id: "t3jgjr2z1",
            target: "g81yux0n1",
            type: "click",
          },
        ],
        $parent: "g81yux0n1",
      },
      oqnvrkg31: {
        type: "text-block",
        specials: { tag: "h2", text: "Gửi Mừng Cưới" },
        id: "oqnvrkg31",
        desktop: {
          animation: { delay: 0, duration: 2, name: "fadeInUp", repeat: null },
          fontSize: "22",
        },
        mobile: { fontSize: 40 },
        $parent: "g81yux0n1",
      },
      p8etkpq11: {
        type: "image-block",
        specials: {
          imageCompression: true,
          src: "https://statics.pancake.vn/web-media/e2/bc/35/38/dc2d9ddf74d997785eb0c802bd3237a50de1118e505f1e0a89ae4ec1-w:592-h:1280-l:497233-t:image/png.png",
        },
        id: "p8etkpq11",
        $parent: "g81yux0n1",
      },
      k0vu3e5e1: {
        type: "text-block",
        specials: {
          tag: "h4",
          text: "MBBANK - NGUYEN TAN DAT<br>8838683860<br>",
        },
        id: "k0vu3e5e1",
        desktop: { fontSize: 17 },
        mobile: { fontSize: 17 },
        $parent: "g81yux0n1",
      },
    },
    extra_css: "",
    extra_script: "",
  },
};
